// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;

    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWaf-4PMDhlkcFO62J-FJKiBfKLkfUeJs',
    appId: '1:319064573214:android:8cae3b3436b51300fb750f',
    messagingSenderId: '319064573214',
    projectId: 'hod-hod-app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwnIuH4Hjl9n3DlEsOuvXokCqhmPeb8wc',
    appId: '1:319064573214:ios:cb7f880237e75b75fb750f',
    messagingSenderId: '319064573214',
    projectId: 'hod-hod-app',
    // databaseURL: '/',
    // storageBucket: 'fils-app.appspot.com',
    // androidClientId: '576292165320-r2n9kmtpku8uv4lenf0cjj1dst8fejfv.apps.googleusercontent.com',
    // iosClientId: '576292165320-r2n9kmtpku8uv4lenf0cjj1dst8fejfv.apps.googleusercontent.com',
    // iosBundleId: 'com.ozone.fils',
  );
  static const FirebaseOptions fuchsia = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    databaseURL: '',
    storageBucket: '',
    androidClientId: '',
    iosClientId: '',
    iosBundleId: '',
  );
}
